name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ubuntu:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Build fbpcf docker image
      run: |
        ./build-docker.sh -u

    - name: Sanity check fbpcf library
      timeout-minutes: 3
      run: |
        ./run-millionaire-sample.sh -u
