name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build fbpcf docker image
      run: |
        ./build-docker.sh -u

    - name: Sanity check fbpcf library
      timeout-minutes: 3
      run: |
        ./run-millionaire-sample.sh -u

  centos:
    runs-on: ubuntu-latest
    if: ${{ false }}  # disable until T92309274 is fixed

    steps:
    - uses: actions/checkout@v2

    - name: Build fbpcf docker image
      run: |
        ./build-docker.sh -c

    - name: Sanity check fbpcf library
      timeout-minutes: 3
      run: |
        ./run-millionaire-sample.sh -c
